---
title: "Is Energy in Synergy with Life"
author: "All_Of_Us"
date: "9/14/2021"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
library(stringr)
library(tidyverse)
library(ggplot2)
library(dplyr)
```

```{r, echo=TRUE}

# Reading the energy dataset
energy_data <- read_csv("https://think.cs.vt.edu/corgis/datasets/csv/energy/energy.csv", 
                        show_col_types = FALSE)
energy_df <- as.tibble(energy_data)

# Creating the arrays for renewable and non renewable resources
consumption_energy_renewable_industrial <- c('Consumption.Industrial.Solar','Consumption.Industrial.Wind','Consumption.Industrial.Geothermal',
                                             'Consumption.Industrial.Hydropower', 
                                             'Consumption.Industrial.Liquefied Petroleum Gases')
consumption_energy_non_renewable_industrial <- c('Consumption.Industrial.Coal','Consumption.Industrial.Distillate Fuel Oil','Consumption.Industrial.Kerosene','Consumption.Industrial.Wood')

# Data Manipulation for Visualization
energy_mutate_df <- energy_df %>% mutate(Total_Consumption_renewable_industrial = rowSums(energy_df[consumption_energy_renewable_industrial]),
Total_Consumption_non_renewable_industrial = rowSums(energy_df[consumption_energy_non_renewable_industrial]))


# Manipulating the data for Consumption of Renewable Resources in Industrial sector(Donut Chart)
top3_Consumption_renewable_industrial <- energy_mutate_df %>% filter(Year == 2014) %>% slice_max(Total_Consumption_renewable_industrial , n = 3) %>% 
  select('State','Year','Consumption.Industrial.Solar','Consumption.Industrial.Wind','Consumption.Industrial.Geothermal','Consumption.Industrial.Hydropower', 'Consumption.Industrial.Liquefied Petroleum Gases', 'Total_Consumption_renewable_industrial', 'Total_Consumption_non_renewable_industrial')

# Visualizing the data in the form of Donut chart
data <- top3_Consumption_renewable_industrial
data_per_thou <- data$Total_Consumption_renewable_industrial
data$fraction <- data_per_thou / sum(data_per_thou)
# Compute the cumulative percentages (top of each rectangle)
data$ymax <- cumsum(data$fraction)
# Compute the bottom of each rectangle
data$ymin <- c(0, head(data$ymax, n=-1))
# Compute label position
data$labelPosition <- (data$ymax + data$ymin) / 2
# Compute a good label
data$label <- paste0(data$State,"\n(", data_per_thou,")")
# Make the plot
 top3_states_rene_chart <- ggplot(data, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=State)) +
  geom_rect() +
  geom_label( x=3.5, aes(y=labelPosition, label=label), size=3) +
  scale_fill_brewer(palette=4) +
  coord_polar(theta="y") +
  xlim(c(2, 4)) + ggtitle("Top 3 States Consumption of Renewable resources(in BTU)")+ theme_void() + 
  theme(legend.position = "none")
top3_states_rene_chart

# Manipulating the data for Consumption of Non-Renewable Resources in Industrial sector
top5_Consumption_non_renewable_industrial <- energy_mutate_df %>% filter(Year == 2014) %>% 
  slice_max(Total_Consumption_non_renewable_industrial, n = 5) %>% 
  select('State','Year','Consumption.Industrial.Coal','Consumption.Industrial.Distillate Fuel Oil','Consumption.Industrial.Wood') %>% glimpse()


# Visualizing the data in the form of Stack Bar chart
pivot_data <- top5_Consumption_non_renewable_industrial %>%
    pivot_longer(cols = -c(State, Year), 
                 names_to = "Types_Of_Energy", 
               values_to = "Consumption")
top5_states_non_rene_chart <- ggplot(pivot_data, aes(x=State, y = Consumption/10000, fill = Types_Of_Energy, label = Consumption )) + geom_bar(width = 0.98, stat="identity") +
  geom_text(size = 3, position = position_stack(vjust = 0.5))+ xlab("State")  + ylab("Consumption in Billion BTU") + ggtitle("Top 5 States Consumption of Non-Renewable(in BTU)")
top5_states_non_rene_chart


## Analysis of Energy Dataset
#  Who are the best and Worst States in consumption of energy resources?
states <- c("Texas", "Pennsylvania")
rene_non_rene_state <-filter(energy_mutate_df, State  %in% states) %>% select('State','Year','Total_Consumption_renewable_industrial','Total_Consumption_non_renewable_industrial') %>% glimpse()

# Gathering the data for both renewable and non-renewable resources usage states
# Comparing the two states based upon their total consumption of all renewable resources
c_rene_indust_graph <- ggplot(rene_non_rene_state) +
  geom_point(aes(x=Year,y=Total_Consumption_renewable_industrial, fill=State,color=State),stat="identity") +
   scale_y_continuous(breaks=c(300000,600000,900000,1200000,1500000,1800000)) +
  ggtitle("Total Consumption of Renewable in Industrial sector from 1960-2014") + xlab("Year") +  ylab("Consumption in Billion BTU") 
c_rene_indust_graph

# Comparing the two states based upon their total consumption of all non_renewable resources
c_non_rene_indust_graph <- ggplot(rene_non_rene_state) +
  geom_point(aes(x=Year,y=Total_Consumption_non_renewable_industrial, fill=State,color=State),stat="identity") +
  scale_y_continuous(breaks=c(300000,600000,900000,1200000,1500000,1800000)) +
  ggtitle("Total Consumption of Non-Renewable in Industrial sector from 1960-2014") + xlab("Year") +  ylab("Consumption in Billion BTU") 
c_non_rene_indust_graph

### Linear model for consumption of Non-Renewable source of energy for Pennsylvania over the years.

rene_non_rene_state_penn <- rene_non_rene_state %>% filter(State == 'Pennsylvania')
model <- lm(Total_Consumption_non_renewable_industrial ~ Year,data = rene_non_rene_state_penn)
summary(model)
x_years <- seq(1960, 2025)
new_df <- tibble(years = x_years)
rene_non_rene_state_pred <- rene_non_rene_state_penn %>% mutate(pred = predict(model))
rene_non_rene_plot <- rene_non_rene_state_pred %>% ggplot() + geom_point(aes(x = Year, y = Total_Consumption_non_renewable_industrial), color = "blue") + scale_x_continuous(breaks=c(1960,1970,1980,1990,2000,2010,2020)) + geom_point(aes(x = Year, y = pred), color = "red") + scale_x_continuous(breaks=c(1960,1970,1980,1990,2000,2010,2020)) +
xlab("Year") +  ylab("Total Consumption of Non-Renewable Source (Industrial)") + ggtitle("Total Consumption of Non-Renewable in Industrial sector from 1960-2014 for state Pennsylvania")
rene_non_rene_plot

# Bias
# Missing data for other renewable resources
# Not using all columns in the dataset

``` 